import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { getConfig } from '../../config';
import { enforceLimit } from '../../lib/limiter';
import { parse } from '../../lib/validate';
import { authenticate } from '../../plugins/guards';
import { subscribeTokenToTopic } from '../console/fcm';

/**
 * Web push: the two routes that let a browser join the broadcast topic the
 * Android app has always been on.
 *
 * The shape is dictated by what a browser can and cannot do. It can ask the
 * user for permission and mint an FCM registration token; it cannot join a
 * topic — the JS SDK has no such call. So the split is:
 *
 *   GET  /app/push-config   what the browser needs to mint a token
 *   POST /me/push-tokens    the token it minted, which we join to the topic
 *
 * Nothing is stored. See the note in ../console/fcm.ts: a token table was the
 * thing this delivery model was designed to avoid, and the app re-registering
 * on every launch makes one unnecessary.
 */

const RegisterInput = z.object({
  // FCM tokens are ~160 characters today and have grown before; the cap is
  // there so a nonsense body fails here rather than inside a URL to Google.
  token: z.string().min(20).max(512),
});

/** Public config. Null when the project's web app has not been set up. */
function webPushConfig(): Record<string, string> | null {
  const cfg = getConfig();
  // The app id is the one value that cannot be guessed or defaulted, so it is
  // what decides whether this is configured at all.
  //
  // FCM_VAPID_KEY is deliberately NOT required. Left empty, the Firebase JS
  // SDK falls back to its own published key, which works — it identifies
  // Firebase to the browser's push service, not us to Firebase. Generating a
  // project key pair in the console (Cloud Messaging → Web Push certificates)
  // is the better long-run answer and is a drop-in: set it here and restart.
  if (!cfg.FCM_WEB_APP_ID) return null;
  const out: Record<string, string> = {
    apiKey: cfg.FCM_WEB_API_KEY,
    authDomain: cfg.FCM_WEB_AUTH_DOMAIN,
    projectId: cfg.FCM_WEB_PROJECT_ID,
    messagingSenderId: cfg.FCM_WEB_SENDER_ID,
    appId: cfg.FCM_WEB_APP_ID,
  };
  if (cfg.FCM_VAPID_KEY) out.vapidKey = cfg.FCM_VAPID_KEY;
  return out;
}

/**
 * The service worker Firebase's JS SDK looks for.
 *
 * It must be at the **origin root** under exactly this name: that is where the
 * SDK's default lookup goes, and it registers it under its own scope
 * (`/firebase-cloud-messaging-push-scope`), which is why this does not collide
 * with `/sw.js` or with the PWA's worker at `/app/sw.js`. One scope holds one
 * registration; three disjoint scopes hold three.
 *
 * Generated rather than a static file so the config in it cannot drift from
 * the config the app is handed by `/app/push-config`. It is served even when
 * push is unconfigured — as an inert file that registers nothing — because a
 * 404 on this path is a confusing error in the browser console for a feature
 * that is simply switched off.
 */
function messagingServiceWorker(): string {
  const cfg = webPushConfig();
  if (!cfg) {
    return `// Cement Desk — web push is not configured on this server.\n`;
  }
  // Pinned to the SDK version firebase_core_web injects into the page. A
  // background handler running a different major than the foreground is the
  // kind of mismatch that fails only on the messages nobody is watching for.
  const SDK = '12.17.0';
  const options = JSON.stringify(
    {
      apiKey: cfg.apiKey,
      authDomain: cfg.authDomain,
      projectId: cfg.projectId,
      messagingSenderId: cfg.messagingSenderId,
      appId: cfg.appId,
    },
    null,
    2,
  );
  return `// Cement Desk — background handler for web push.
//
// Generated by the backend (src/modules/push/routes.ts) so its Firebase
// config can never drift from the one /api/v1/app/push-config hands the app.
// Do not add caching here: the PWA's own service worker at /app/sw.js owns
// that, and this one is registered under a different scope purely so Firebase
// has somewhere to deliver a push event when no tab is open.
importScripts('https://www.gstatic.com/firebasejs/${SDK}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${SDK}/firebase-messaging-compat.js');

firebase.initializeApp(${options});

// Constructing it is the whole job. Our broadcasts carry a \`notification\`
// block, so the SDK renders them itself — an onBackgroundMessage handler here
// would only duplicate the notification, which is a well-known way to show
// every announcement twice.
firebase.messaging();

// Clicking the notification should land in the app, not open a second copy of
// it beside the one already running.
self.addEventListener('notificationclick', (event) => {
  const link = (event.notification && event.notification.data &&
    event.notification.data.FCM_MSG &&
    event.notification.data.FCM_MSG.notification &&
    event.notification.data.FCM_MSG.notification.click_action) || '/app/';
  event.notification.close();
  event.waitUntil((async () => {
    const target = new URL(link, self.location.origin);
    const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of all) {
      if (new URL(client.url).pathname.startsWith('/app/') && 'focus' in client) {
        return client.focus();
      }
    }
    return self.clients.openWindow(target.href);
  })());
});
`;
}

/** Root-level, outside /api/v1: Firebase looks for this exact path. */
export function registerPushServiceWorkerRoute(app: FastifyInstance): void {
  app.get('/firebase-messaging-sw.js', async (_req, reply) =>
    reply
      .type('text/javascript; charset=utf-8')
      // Never cached. It carries config, and a stale copy of a rotated VAPID
      // key is a browser that silently stops receiving anything.
      .header('cache-control', 'no-store')
      .header('service-worker-allowed', '/')
      .send(messagingServiceWorker()),
  );
}

export function registerPushRoutes(app: FastifyInstance): void {
  /**
   * Unauthenticated, like `/app/sponsor`: it is public configuration, and the
   * app reads it before it knows whether it will ever need it.
   */
  app.get('/app/push-config', async (_req, reply) => {
    void reply.header('cache-control', 'public, max-age=300');
    return { web: webPushConfig() };
  });

  /**
   * `authenticate` rather than `authenticateVerified`: the announcements this
   * subscribes to are how we would tell someone their verification mail went
   * astray, so gating it behind verification is exactly backwards.
   */
  app.post('/me/push-tokens', { preHandler: [authenticate] }, async (req, reply) => {
    if (!webPushConfig()) {
      // Not an error the user can act on, and not a server fault either.
      return reply.code(204).send();
    }
    const { token } = parse(RegisterInput, req.body);
    // Generous, because the app posts only when the token has changed — a
    // device hitting this ten times in an hour is either rotating badly or
    // is not our app.
    enforceLimit(`push:${req.userId}`, 10, 3600_000);
    await subscribeTokenToTopic(token);
    return reply.code(204).send();
  });
}
